// Code generated by command: go run caller.go -out caller.s -stubs caller.go. DO NOT EDIT.

#include "textflag.h"

// func CallJit(f uint64, args uint64, buf uint64, l uint64) uint64
TEXT ·CallJit(SB), NOSPLIT|NOFRAME, $512-40
	MOVQ f+0(FP), DI
	MOVQ args+8(FP), SI
	MOVQ buf+16(FP), DX
	MOVQ l+24(FP), CX
	MOVQ SP, BX
	ADDQ $+512, SP
	MOVQ $-16, AX
	ANDQ AX, SP
	CALL call_jit_function+0x00(SB)
	MOVQ BX, SP
	MOVQ AX, ret+32(FP)
	RET
