// Code generated by command: go run caller.go -out caller.s -stubs caller.go. DO NOT EDIT.

package caller

// Calls a jit_function_t without locking an OS thread.
// - f: a jit_function value
// - args: a pointer to an []uint64 argument array, probably from unsafe.Pointer(&args[0])
// - stack: stack size needed
func CallJit(f uint64, args []uint64, stack uint64) uint64
